# Generated by Django 5.1.2 on 2024-11-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('subject', models.TextField()),
                ('Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.TextField()),
                ('c_name', models.TextField()),
                ('dis', models.TextField()),
                ('duration', models.IntegerField()),
                ('Course_fees', models.IntegerField()),
                ('img', models.FileField(upload_to='')),
            ],
        ),
    ]
